In [4]:
import pandas as pd
import matplotlib.pyplot as plt
# import seaborn as sns
import numpy as np
from matplotlib import font_manager, rc
font_path = "./malgun.ttf"
font_name = font_manager.FontProperties(fname=font_path).get_name()
rc('font', family=font_name)

In [8]:
df1=pd.read_excel('20230224113125.xlsx')

In [7]:
# 1. 원본 데이터에서 필요한 데이터(전체 -> 연령별, 전체 -> 소득별, 남자 전체 + 여자 전체)를 슬라이싱한다. => df1, df2, df3
# 2. 슬라이싱한 3가지의 데이터 프레임을 필요한 형태로 가공한다.
# 3. 가공한  3가지의 데이터 프레임을 각각 그래프로 그린다.

In [ ]:
df1=df1.iloc

In [9]:
df1

,성별(1),특성별(1),특성별(2),2005,2005.1,2005.2,2007,2007.1,2007.2,2008,...,2017.2,2018,2018.1,2018.2,2019,2019.1,2019.2,2020,2020.1,2020.2
0,성별(1),특성별(1),특성별(2),응답자수 (명),분율 (%),표준오차,응답자수 (명),분율 (%),표준오차,응답자수 (명),...,표준오차,응답자수 (명),분율 (%),표준오차,응답자수 (명),분율 (%),표준오차,응답자수 (명),분율 (%),표준오차
1,전체,전체,19세이상,7801,28.8,0.7,2980,25,1.1,6797,...,0.8,6183,21.1,0.7,6190,20.2,0.7,5858,19.2,0.8
2,NaN,NaN,19세이상(표준화),7801,28.8,0.7,2980,25.3,1.2,6797,...,0.9,6183,22.4,0.8,6190,21.5,0.8,5858,20.6,0.8
3,NaN,연령별1,19-29세,1336,31.6,1.4,339,27.8,2.9,892,...,2,762,23.8,1.9,749,24.8,2,798,21.9,1.6
4,NaN,NaN,30-39세,1741,33,1.4,635,32,2.1,1413,...,1.9,909,24.7,1.7,915,24,1.7,766,23,1.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,NaN,소득수준(표준화)별,하,887,8.6,1.2,324,11.3,3.3,773,...,1.7,694,10.7,1.5,684,13,1.8,632,12.1,1.8
69,NaN,NaN,중하,823,6,0.9,333,7.3,1.9,777,...,1.2,696,10.6,1.9,681,6.5,1.5,637,9.1,1.6
70,NaN,NaN,중,838,4.8,0.9,329,2.7,0.9,757,...,1.2,693,6.9,1.2,686,7.9,1.4,650,5.3,1.2
71,NaN,NaN,중상,854,4.3,0.8,330,2.1,0.7,769,...,1.3,684,5.6,1.2,696,4.5,1,651,4.8,1.3
72,NaN,NaN,상,848,4.9,0.9,334,2.7,1.1,756,...,0.9,693,3.2,0.9,684,1.8,0.6,647,2.4,0.7