In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from matplotlib import font_manager, rc
font_path = "./malgun.ttf"
font_name = font_manager.FontProperties(fname=font_path).get_name()
rc('font', family=font_name)

plt.rcParams['axes.unicode_minus'] = False

In [3]:
df1 = pd.read_excel('GRDP_시도.xlsx')  # GRDP             =====================> 정규화
df2 = pd.read_excel('경제성장률_시도__20230222224924.xlsx')   # 경제성장률                =======> 정규화
df4 = pd.read_excel('경제활동인구_시도__20230222225929.xlsx')  # 경제활동인구====> 비율    =======> 정규화
df3 = pd.read_excel('고령인구비율_시도_시_군_구__20230222225425.xlsx')

,경제활동별(1),시도별(1),1985,1985.1,1986,1986.1,1987,1987.1,1988,1988.1,...,2017,2017.1,2018,2018.1,2019,2019.1,2020,2020.1,2021,2021.1
0,경제활동별(1),시도별(1),명목,실질,명목,실질,명목,실질,명목,실질,...,명목,실질,명목,실질,명목,실질,명목,실질,명목,실질
1,지역내총생산(시장가격),전국,91625288,278804522,107026220,308977877,124635951,346934339,149134859,388842170,...,1840348850,1762932983,1902527946,1814075680,1927421209,1854370144,1944644393,1842426414,2076254437,1919305433
2,NaN,서울특별시,23118019,77310769,27275885,85661549,32075111,97480930,37559452,107819304,...,404079600,389584629,423742112,403605888,435927212,414092568,444544909,417638547,471730788,432406018
3,NaN,부산광역시,7009992,21773910,7983184,23751051,9294215,26214172,10674301,28703583,...,87835601,85441974,89979896,86889875,93012134,89105372,91286486,85962709,98651991,87906722
4,NaN,대구광역시,3940271,13889560,4684045,15391591,5589706,17380068,6345089,18711134,...,54832958,52721214,56714479,53964991,58094694,54762237,57725389,53668577,60865535,56026338
5,NaN,인천광역시,4227110,13731212,4921002,15072642,5737030,17114977,7062631,19699166,...,88547364,85791563,88735401,86426825,90040500,87963593,89615465,84907539,97894444,89984023
6,NaN,광주광역시,-,-,-,-,2330249,7421376,3068929,8961220,...,37743917,36384616,39805406,38216077,41519553,39624032,42068384,39530642,43454904,41118247
7,NaN,대전광역시,-,-,-,-,-,-,-,-,...,40537224,38772485,41308348,39135729,43092218,40684092,44393136,41208249,46379776,42368245
8,NaN,울산광역시,-,-,-,-,-,-,-,-,...,75750070,72968962,73647537,71344390,74654628,72024599,69363394,67136435,77683017,69621279
9,NaN,세종특별자치시,-,-,-,-,-,-,-,-,...,10632043,10140164,11101861,10423610,11855276,11091040,12703589,11647981,13898917,12489323
10,NaN,경기도,12713559,35376012,15529457,41139886,18759741,48500639,23298253,55559190,...,451426420,426172886,479822189,451914662,477413452,462288338,491298336,470022670,527046766,496672331
11,NaN,강원도,3772429,13811635,4315140,14954820,4924871,16025537,5481832,16714920,...,45511732,43761362,46925797,44574334,48822640,46064137,48656564,44829136,50659583,46476220
12,NaN,충청북도,3130073,9306817,3293432,9498358,3666631,10025030,4325367,11167116,...,65312366,61953139,69636876,65830010,69419635,66927772,69583769,65926194,74766578,70139551
13,NaN,충청남도,5890520,18357268,6869336,20401171,7639501,21765224,9184167,24439952,...,115557697,110165655,115534184,110873163,113488325,112310782,115531056,112762058,124586926,118002148
14,NaN,전라북도,3458409,12210367,3964616,13208204,4352185,13745742,5125538,15630632,...,49348477,47553099,50595318,48350793,51997535,49506041,52820485,49116252,55461662,50398818
15,NaN,전라남도,6617512,22969944,7495647,24558114,6280628,20682782,7700766,23476717,...,73732402,71340179,75424584,72888289,76948280,74618019,78819152,74972494,88266312,77027126
16,NaN,경상북도,6986570,16624884,8257601,19196053,9736551,21448162,12070377,24585565,...,110027724,104429785,108782638,103149107,106805459,104417627,105771509,101370158,112784772,104960491
17,NaN,경상남도,9937947,24375901,11519410,26803117,13132496,29672028,15906954,33557592,...,109492183,106561346,110720199,107224316,114020931,109370902,110847012,103425415,112073936,105347557
18,NaN,제주특별자치도,822877,3135822,917465,3246888,1117036,3665368,1331203,4011296,...,19981072,19144657,20051121,18968300,20308737,19186190,19615758,17957495,20048530,18175224