In [1]:
import pandas as pd
import matplotlib.pyplot as plt
# import seaborn as sns
import numpy as np
from matplotlib import font_manager, rc
font_path = "./malgun.ttf"
font_name = font_manager.FontProperties(fname=font_path).get_name()
rc('font', family=font_name)

In [4]:
df=pd.read_excel('국가별_원유수입_20230225172627.xlsx')
# df.to_excel('국가별_원유수입_20230225172627.xlsx', index=False)

In [5]:
df

,국가별(1),국가별(2),1998,1999,2000,2001,2002,2003,2004,2005,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,합계,소계,819094,874090,893943,859367,790992,804809,825790,843203,...,947292,915075,927524,1026107,1078119,1118167,1116281,1071923,980259,960147
1,아시아,소계,113494,93517,112669,130033,136756,100721,116287,111937,...,88190,97047,88623,106263,72756,97233,122832,107943,88493,113932
2,NaN,중국,24192,3872,3881,2083,3696,7096,8602,7061,...,-,-,-,-,-,-,-,-,-,-
3,NaN,필리핀,-,-,-,-,1262,-,302,-,...,4986,4412,3596,2995,3059,1992,988,1291,585,718
4,NaN,태국,1991,-,709,-,2741,936,2621,2345,...,2384,2449,-,-,300,525,262,-,-,281
5,NaN,말레이지아,18156,19988,17732,19838,14247,11101,13785,13037,...,4909,5099,4353,2833,1554,3606,2803,1556,1582,315
6,NaN,인도네시아,33599,41726,36762,45228,42457,33672,38104,37703,...,20588,13242,9080,8475,6412,8624,7008,2742,351,586
7,NaN,방글라데시,-,-,-,-,-,-,-,-,...,-,-,-,121,-,-,-,-,-,-
8,NaN,인도,224,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
9,NaN,브루나이,13786,8045,8649,9631,11508,11247,10897,10558,...,9923,7606,5702,4808,3001,2606,3213,1873,1481,-
10,NaN,호주,14252,15495,34990,32879,39552,25396,32068,31879,...,7723,15992,20861,17694,12049,11679,11092,7886,14564,22009
11,NaN,뉴질랜드,-,-,-,-,-,-,-,-,...,-,-,214,509,297,705,421,-,-,165
12,NaN,베트남,1811,628,-,470,437,-,1390,-,...,7125,8140,2646,3090,2058,2424,1636,2289,201,210
13,NaN,미얀마,-,-,-,1218,1687,-,-,388,...,-,-,-,-,367,-,-,-,-,-
14,NaN,파푸아뉴기니,1944,-,-,-,-,-,-,660,...,-,-,-,1332,-,-,650,1632,3872,3239
15,NaN,러시아,3539,3763,9946,18685,15049,7025,8517,8305,...,30551,40107,34480,51096,39360,38570,39323,30740,46929,53748
16,NaN,카자흐스탄,-,-,-,-,4121,4247,-,-,...,-,-,7690,13310,4299,26501,55434,57933,18928,32662
17,NaN,아제르바이젠,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
18,아프리카,소계,61907,109560,67749,39155,35877,34156,42874,34424,...,9233,8096,25301,26691,30496,28189,40901,19928,24549,32000
19,NaN,튀니지,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,299,-,-,-
20,NaN,알제리,-,-,-,-,-,-,2010,1981,...,699,674,1107,-,-,6563,15738,6979,8733,8577
21,NaN,리비아,-,-,-,-,-,-,-,-,...,5280,3764,6768,2727,6533,11262,3920,1548,-,-
22,NaN,이집트,5230,15191,888,-,1048,1038,5005,3161,...,-,-,-,-,-,-,-,-,-,-
23,NaN,앙골라,11492,40080,23852,8708,7702,8188,3866,-,...,-,208,-,1903,2808,-,-,-,-,-
24,NaN,카메룬,700,3964,-,-,-,1860,8473,9162,...,303,-,-,950,437,952,-,525,308,-
25,NaN,콩고,18746,19688,19255,16452,17727,12072,5521,8180,...,-,-,2763,965,1550,-,1261,-,-,4679
26,NaN,가봉,2826,3670,5744,4873,2026,3853,975,1846,...,2296,1319,5832,6425,6650,1302,7250,4377,2627,7480
27,NaN,나이지리아,21999,20756,11260,3910,1899,2805,11622,6504,...,-,-,836,2086,1300,-,8973,3873,9779,7325
28,NaN,수단,-,2142,4754,4257,1595,2015,3860,2644,...,-,569,-,-,-,-,571,571,-,-
29,NaN,적도기니아,915,4069,1995,956,3879,2324,1542,946,...,655,1562,7996,11635,11219,8110,2889,2055,3102,3939
30,아메리카,소계,17594,27896,21365,25469,30282,28543,21447,5363,...,314,329,10053,23255,30080,44453,95094,187735,173044,204188
31,NaN,캐나다,-,-,-,1672,942,965,-,-,...,-,-,383,-,-,-,1193,1377,523,5776
32,NaN,미국,8719,11966,6341,-,-,-,-,-,...,-,-,1663,2909,2445,13429,60942,137894,104409,118668
33,NaN,멕시코,-,-,-,-,-,-,-,-,...,-,-,-,14886,27635,31024,31966,45902,50162,54400
34,NaN,베네주엘라,-,-,-,1475,13,60,-,-,...,-,-,-,-,-,-,-,-,-,-
35,NaN,브라질,-,-,-,3996,10360,11135,6799,4721,...,-,-,-,-,-,-,-,-,16926,23265
36,NaN,에쿠아도르,8875,15236,12384,12853,14234,9483,13662,643,...,-,-,2697,3534,-,-,-,1875,-,1080
37,NaN,페루,-,694,2640,696,-,-,-,-,...,-,-,-,-,-,-,-,688,-,-
38,NaN,아르헨티나,-,-,-,4778,4733,6900,987,-,...,314,-,-,-,-,-,-,-,-,-
39,NaN,콜롬비아,-,-,-,-,-,-,-,-,...,-,329,5041,1926,-,-,992,-,1025,1000
40,NaN,볼리비아,-,-,-,-,-,-,-,-,...,-,-,270,-,-,-,-,-,-,-
41,중동,소계,622005,632067,686916,661649,579865,639453,645183,689356,...,805971,786813,778923,844637,926201,913446,820994,752564,676409,574430
42,NaN,이란,67502,81944,81251,80413,51512,63682,64974,70767,...,56146,48214,44923,42400,111942,147873,58202,33230,-,-
43,NaN,이라크,4992,7242,17819,3201,3759,1931,11358,14972,...,93122,90739,71151,126635,138328,126203,138131,118412,77196,59993
44,NaN,쿠웨이트,66894,53284,66627,64407,56996,65885,64659,79679,...,137647,139853,136546,141856,159273,160368,162005,150587,129699,101721
45,NaN,카타르,34879,37301,45722,42157,35330,46780,45581,53122,...,103825,86090,100127,123228,88150,64934,65980,64293,59735,50610
46,NaN,아랍에미레이트,122022,117405,128064,128405,105905,138869,145598,150608,...,86536,110809,108472,99835,87743,90971,72030,88811,77563,56809
47,NaN,사우디아라비아,234450,241747,264925,255432,240765,250473,253849,249337,...,303049,286588,292592,305779,324448,319221,323174,296871,325808,281774
48,NaN,예멘,15811,17567,19834,15318,17582,7787,3284,5813,...,-,-,-,-,-,-,-,-,-,-
49,NaN,오만,57195,56001,46632,53639,42053,40927,32832,38799,...,8761,3543,6516,2897,16317,3876,1471,360,3907,6574
50,NaN,중립지대,18259,19578,16043,18678,25963,23118,23048,26258,...,16884,20976,18595,2006,-,-,-,-,2501,16949
51,유럽,소계,4095,11050,5245,3061,8212,1936,0,2124,...,43585,22790,24625,25261,18587,34847,36461,3753,17765,35597
52,NaN,노르웨이,4095,11050,5245,3061,7014,1933,-,-,...,18819,2194,-,322,-,735,5101,728,8631,17007
53,NaN,영국,-,-,-,-,1197,3,-,2124,...,24765,20595,24625,24940,18587,34112,31360,3025,9134,18589